# Generated by Django 3.0.7 on 2020-09-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_profile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, choices=[('Chairperson', 'Chairperson'), ('Vice Chairperson', 'Vice Chairperson'), ('Secretary', 'Secretary'), ('Vice Secretary', 'Vice Secretary'), ('IT Director', 'IT Director')], max_length=225),
        ),
    ]
