# Generated by Django 3.0.7 on 2020-09-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hope', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
    ]
