# Generated by Django 3.0.7 on 2020-09-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hope', '0004_auto_20200912_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Potfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('hospital', 'Hospital'), ('orphanage', 'Orphanage'), ('prisons', 'Prisons'), ('drug_addiction', 'Drug addiction center')], max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('img_url', models.URLField(max_length=2000)),
            ],
        ),
    ]
