# Generated by Django 3.0.7 on 2020-09-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hope', '0005_potfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='potfolio',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
    ]
