# Generated by Django 3.0.7 on 2020-09-13 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hope', '0006_potfolio_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Potfolio',
            new_name='Portfolio',
        ),
    ]
